### ISSUE TITLE
Push Msg to part

### ISSUE THREAD

**Issue by ritcoder** [debois/elm-parts#1]
Hi,
How do you push a message to part?

I'm having a scenario where if the context changes, the parent will update the child part if they require that.

```
--in parent

update msg model =
  case msg of
    NewContext ctx ->
      -- update local context
      -- partA.update (NewContext ctx) ...
      -- partB.update (NewContext ctx) ...

```

**Comment by debois** [comment]
What's wrong with the suggestion above?

**Comment by ritcoder** [comment]
Nothing actually. It works. Just wanted to know if there was a `part specifc way of doing it`.
