### ISSUE TITLE
Introduction of Index

### ISSUE THREAD

**Issue by ritcoder** [debois/elm-parts#2]
Hi,
I've upgraded my copy of `Part` to `0.17` as part of migration of the entire project. This copy is based on the very first version you published. In looking at the new part code, there are quite a number of changes. Of interest is the introduction of `List Int` instead of `Int` as the dictionary key. Since almost all components in my project are implemented on Part, can you elaborate on this change and what it offers? I'm looking at updating the local copy so it is aligned to the current version by close of week.

**Comment by debois** [comment]
If you have dynamically generated components (say, a list of buttons), you want to make sure that each button gets a unique index. This can be a pain to ensure by hand, but with a list, you can say by convention that your regular components have indexes `[1]`, `[2]`, and so forth, but give your dynamically generated buttons indices `[0,1]`, `[0,2]`, `[0,3]`, etc. 

The second change is that adding observers are now arguments to the view functions. Some elm-mdl users preferred it this way.

**Comment by ritcoder** [comment]
Oh ok. I'm yet to come across that scenario from my end but I guess that change wont have any negative effect on my code. Most of the components are `singleton`s.

For the observers, is there any advantage in adding it to the view functions? I'm using the initial version where it is at the time of creating the part. Seems like the good place to define the observers.

**Comment by debois** [comment]
Same problem: If you are generating lists of elements dynamically (say, a list of checkboxes), you won't know how many until you are in the view and have the model, and you similarly won't know what messages (actions) you want until that point.
