### ISSUE TITLE
Any plans to port it to 0.17

### ISSUE THREAD

**Issue by ghost** [debois/elm-parts#3]
I'm new to elm but after few days of learning it I already feel the pain of lack of compose-ability. The description of the elm-parts seams to second that. 
Now, it is quite hard to apply patterns design for 0.16 to 0.17 for someone just started to learn elm.
Do you have any plans to port it to 0.17?

**Comment by debois** [comment]
Done, but it did require major changes. The `Observation` mechanism had to go, but could conceivably be put back in—open an issue if you need it.
