### ISSUE TITLE
Type annotation on 'view' fails when using lift with onInput

### ISSUE THREAD

**Issue by demsullivan** [debois/elm-parts#4]
I originally came across this in my own code when playing with elm-parts, but I've reproduced it in a simpler example. In the gist below, I took the structure of the counter-list-part example in the elm-parts repo, and updated it to reflect the "reversed text" example from the Elm tutorial.

Using lift with an onInput results in the following error:

```
The type annotation for `view` does not match its definition.

38| view : (Msg -> m) -> Model -> Html m
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    (Msg -> a) -> { value : String } -> Html a

But I am inferring that the definition has this type:

    ((String -> Msg) -> String -> a) -> { b | value : String } -> Html a
```

See Gist here: https://gist.github.com/demsullivan/2febbc3c2a523c98ef7d55e1384e055b

**Comment by debois** [comment]
Shouldn't [this line](https://gist.github.com/demsullivan/2febbc3c2a523c98ef7d55e1384e055b#file-textreverse-elm-L42)  be `... onInput (SetText >> lift) ...` ?

**Comment by demsullivan** [comment]
Yep, that fixes it! I hadn't seen it written like that before and I'm still learning... since the counter-list example is just `onClick (lift Increment)` I figured it was the same for `onInput`.

Thanks!

**Comment by debois** [comment]
Welcome :)
